-- plugins manager setup
require('plugins')
require('theme')
require('options')
require('keymaps')
require('plugin_config.winbar')
require('plugin_config.mini-indentscope')
require('plugin_config.mini-comment')
require('plugin_config.lualine')
require('plugin_config.nvim-tree')
require('plugin_config.telescope')
require('plugin_config.flash')
require('plugin_config.tagbar')
-- require('plugin_config.bufferline')
require('plugin_config.luatab')
require('plugin_config.illuminate')
require('plugin_config.lsp')
require('plugin_config.nvim-cmp')
require('plugin_config.vim-better-whitespace')
require('plugin_config.vim-spectre')
require('plugin_config.toggleterm')
