# tmux setting
set -g mouse on
set -g focus-events on
set -g escape-time 0
set -g base-index 1
set -g default-terminal "screen-256color"
set -ga terminal-overrides ",*256col*:Tc"
set -g status-style "bg=#262626,fg=#cc241d"
set -g status-left-length 100
set -g status-right-length 100
set -g status-left "#[fg=#444444,bg=#eeeeee,bold] #S #[default] " # session-name
set -g status-right "#[fg=#d0d0d0,bg=#444444] %Y-%m-%d %H:%M #[default]#[fg=#444444,bg=#eeeeee,bold] #{host} #[default]"
set -g pane-active-border-style "fg=#cc241d"
set -g pane-border-style "fg=#262626"
setw -g pane-base-index 1
setw -g window-status-format " #I #W"
setw -g window-status-current-format " #I #W"
setw -g window-status-current-style "fg=#fae81d"
setw -g automatic-rename off
setw -g mode-keys vi

# key bind for global
unbind C-b
set -g prefix ^A
bind a send-prefix
bind r source-file ${HOME}/.tmux.conf \; display-message "source-file reloaded"
bind R move-window -r \; display-message "window renumber order"
# key bind for session
bind -n 'M-s' choose-session -N
# key bind for window
bind k confirm kill-window
bind -n 'F11' previous-window
bind -n 'F12' next-window
bind -n 'S-F11' run 'tmux swap-window -t -1; tmux select-window -t -1'
bind -n 'S-F12' run 'tmux swap-window -t +1; tmux select-window -t +1'
bind - split-window -v
bind | split-window -h

# key bind for pane
bind -n 'M-m' resize-pane -Z
bind -n 'M-k' select-pane -U
bind -n 'M-j' select-pane -D
bind -n 'M-h' select-pane -L
bind -n 'M-l' select-pane -R
bind -n 'M-{' swap-pane -U
bind -n 'M-}' swap-pane -D
bind -r -n 'M-K' resize-pane -U 5
bind -r -n 'M-J' resize-pane -D 5
bind -r -n 'M-H' resize-pane -L 5
bind -r -n 'M-L' resize-pane -R 5
# key bind for copy-mode
bind -T copy-mode-vi v send -X begin-selection
bind -T copy-mode-vi y send-keys -X copy-pipe-and-cancel
